networks:
  default:
    ipam:
      config:
        - subnet: 10.110.0.0/16
          ip_range: 10.110.0.16/29
          gateway: 10.110.0.17

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    environment:
      TZ: ${TZ:-Europe/Stockholm}
    restart: unless-stopped
    volumes:
      - ./ha:/config
    develop:
      watch:
        - path: ./custom_components/hole
          action: sync+restart
          target: /config/custom_components/hole
    privileged: true
    networks:
      - default
    links:
      - pihole
    depends_on:
      - pihole
    ports:
      - 80:8123
  pihole:
    hostname: pi.hole
    container_name: pi.hole
    image: "pihole/pihole:latest"
    environment:
      TZ: ${TZ:-Europe/Stockholm}
      FTLCONF_webserver_api_password: ${PIHOLE_FTL_PASSWORD:-correct horse battery staple}
    ports:
      - 8080:80/tcp
    volumes:
      - ./pihole:/etc/pihole