networks:
  default:
    ipam:
      config:
        - subnet: 10.110.0.0/16
          ip_range: 10.110.0.16/29
          gateway: 10.110.0.17

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    environment:
      TZ: Europe/Stockholm
    restart: unless-stopped
    volumes:
      - ../config:/config
      - ../custom_components:/config/custom_components:ro
    develop:
      watch:
        - path: ./custom_components/hole
          action: sync+restart
          target: /config/custom_components/hole
    privileged: true
    networks:
      - default
    ports:
      - 80:8123