DOMAIN="pihole_v6"

DEFAULT_HOST = "http://pi.hole"
DEFAULT_LOCATION = "api"
DEFAULT_PORT = 80
DEFAULT_VERIFY_SSL = False
DEFAULT_API_KEY = ""
DEFAULT_NAME = "pihole"

SERVICE_DISABLE = "disable"
SERVICE_DISABLE_ATTR_DURATION = "duration"

CONF_SID = "X-FTL-SID"
FONG_CSRF = "X-FTL-CSRF"